// Generated by cpp11: do not edit by hand
// clang-format off

#include "faststochtree_types.h"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// bindings.cpp
external_pointer<bart::BARTModel> fit_bart_cpp(doubles_matrix<> X, doubles y, doubles_matrix<> X_test, int n_burnin, int n_samples, int seed, list config);
extern "C" SEXP _faststochtree_fit_bart_cpp(SEXP X, SEXP y, SEXP X_test, SEXP n_burnin, SEXP n_samples, SEXP seed, SEXP config) {
  BEGIN_CPP11
    return cpp11::as_sexp(fit_bart_cpp(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(X), cpp11::as_cpp<cpp11::decay_t<doubles>>(y), cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(X_test), cpp11::as_cpp<cpp11::decay_t<int>>(n_burnin), cpp11::as_cpp<cpp11::decay_t<int>>(n_samples), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<list>>(config)));
  END_CPP11
}
// bindings.cpp
external_pointer<bart::BARTModel> fit_xbart_cpp(doubles_matrix<> X, doubles y, doubles_matrix<> X_test, int n_burnin, int n_samples, int seed, list config);
extern "C" SEXP _faststochtree_fit_xbart_cpp(SEXP X, SEXP y, SEXP X_test, SEXP n_burnin, SEXP n_samples, SEXP seed, SEXP config) {
  BEGIN_CPP11
    return cpp11::as_sexp(fit_xbart_cpp(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(X), cpp11::as_cpp<cpp11::decay_t<doubles>>(y), cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(X_test), cpp11::as_cpp<cpp11::decay_t<int>>(n_burnin), cpp11::as_cpp<cpp11::decay_t<int>>(n_samples), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<list>>(config)));
  END_CPP11
}
// bindings.cpp
doubles_matrix<> predict_cpp(external_pointer<bart::BARTModel> model, doubles_matrix<> X_new);
extern "C" SEXP _faststochtree_predict_cpp(SEXP model, SEXP X_new) {
  BEGIN_CPP11
    return cpp11::as_sexp(predict_cpp(cpp11::as_cpp<cpp11::decay_t<external_pointer<bart::BARTModel>>>(model), cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(X_new)));
  END_CPP11
}
// bindings.cpp
doubles_matrix<> test_samples_cpp(external_pointer<bart::BARTModel> model);
extern "C" SEXP _faststochtree_test_samples_cpp(SEXP model) {
  BEGIN_CPP11
    return cpp11::as_sexp(test_samples_cpp(cpp11::as_cpp<cpp11::decay_t<external_pointer<bart::BARTModel>>>(model)));
  END_CPP11
}
// bindings.cpp
doubles sigma2_samples_cpp(external_pointer<bart::BARTModel> model);
extern "C" SEXP _faststochtree_sigma2_samples_cpp(SEXP model) {
  BEGIN_CPP11
    return cpp11::as_sexp(sigma2_samples_cpp(cpp11::as_cpp<cpp11::decay_t<external_pointer<bart::BARTModel>>>(model)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_faststochtree_fit_bart_cpp",       (DL_FUNC) &_faststochtree_fit_bart_cpp,       7},
    {"_faststochtree_fit_xbart_cpp",      (DL_FUNC) &_faststochtree_fit_xbart_cpp,      7},
    {"_faststochtree_predict_cpp",        (DL_FUNC) &_faststochtree_predict_cpp,        2},
    {"_faststochtree_sigma2_samples_cpp", (DL_FUNC) &_faststochtree_sigma2_samples_cpp, 1},
    {"_faststochtree_test_samples_cpp",   (DL_FUNC) &_faststochtree_test_samples_cpp,   1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_faststochtree(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
