# Generated by cpp11: do not edit by hand

fit_bart_cpp <- function(X, y, X_test, n_burnin, n_samples, seed, config) {
  .Call(`_faststochtree_fit_bart_cpp`, X, y, X_test, n_burnin, n_samples, seed, config)
}

fit_xbart_cpp <- function(X, y, X_test, n_burnin, n_samples, seed, config) {
  .Call(`_faststochtree_fit_xbart_cpp`, X, y, X_test, n_burnin, n_samples, seed, config)
}

predict_cpp <- function(model, X_new) {
  .Call(`_faststochtree_predict_cpp`, model, X_new)
}

test_samples_cpp <- function(model) {
  .Call(`_faststochtree_test_samples_cpp`, model)
}

sigma2_samples_cpp <- function(model) {
  .Call(`_faststochtree_sigma2_samples_cpp`, model)
}
